name:                hledger-format
version:             0.1.0.0
github:              "neoncrisis/hledger-format"
license:             BSD3
author:              "Oz Lopez"
maintainer:          "oz.lopez@superluminal.me"
copyright:           "2018 Oz Lopez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/neoncrisis/hledger-format#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- directory
- filepath
- hledger-lib
- optparse-applicative
- string-conversions
- text
- time

library:
  source-dirs: src

executables:
  hledger-format:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hledger-format

tests:
  hledger-format-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hledger-format
